name: tuberiatendencias

on: 
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        env:
            SPECFLOW_PROJECT: SpecFlow.Ejemplo
        runs-on: ubuntu-latest
        container: sergiorjuela/mono:latest
        steps:
            -   name: Checkout project
                uses: actions/checkout@v2

            -   name: Setup .NET Core SDK 3.1.x
                uses: actions/setup-dotnet@v1.7.2
                with:
                    dotnet-version: '3.1.x'

            -   name: Build
                run: dotnet build

            -   name: Test
                run: dotnet test

            -   name:  Instalar generador de documentacion
                run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

            -   name: Generate LivingDoc documentation
                run: |
                    export PATH="$PATH:/root/.dotnet/tools"
                    livingdoc test-assembly ./$SPECFLOW_PROJECT/bin/Debug/netcoreapp3.1/$SPECFLOW_PROJECT.dll -t ./$SPECFLOW_PROJECT/bin/Debug/netcoreapp3.1/TestExecution.json --output ./docs/index.html

            -   name: Instalar Rsync
                run: sudo apt-get install -y rsync

            -   name: Deploy 
                uses: JamesIves/github-pages-deploy-action@4.1.3 # plugin para deplegar la doc.
                with:
                    branch: gh-pages # Rama donde se despliega la documentación.
                    folder: ./docs # folder donde se despliega la documentación.
        

            


